[package]
name = "maturin_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "maturin_test"
crate-type = ["cdylib"]

[dependencies]
thiserror = "1.0.0"
anyhow = "1.0.51"
pyo3 = { version = "0.16.5", features = ["extension-module"] }
